apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sender
  labels:
    app: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
      - name: sender
        image: fahadrauf/sender
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
